using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Data.Entity;
namespace RealEstateWebsite.Models
{
    public class DataInitializer: DropCreateDatabaseIfModelChanges<DataContext>
    {
        protected override void Seed(DataContext context)
        {
            var sehir = new List<Sehir>()
            {
                new Sehir() { SehirAd = "ADANA" },
new Sehir() { SehirAd = "ADIYAMAN" },
new Sehir() { SehirAd = "AFYONKARAHİSAR" },
new Sehir() { SehirAd = "AĞRI" },
new Sehir() { SehirAd = "AMASYA" },
new Sehir() { SehirAd = "ANKARA" },
new Sehir() { SehirAd = "ANTALYA" },
new Sehir() { SehirAd = "ARTVİN" },
new Sehir() { SehirAd = "AYDIN" },
new Sehir() { SehirAd = "BALIKESİR" },
new Sehir() { SehirAd = "BILECIK" },
new Sehir() { SehirAd = "BİNGÖL" },
new Sehir() { SehirAd = "BİTLİS" },
new Sehir() { SehirAd = "BOLU" },
new Sehir() { SehirAd = "BURDUR" },
new Sehir() { SehirAd = "BURSA" },
new Sehir() { SehirAd = "ÇANAKKALE" },
new Sehir() { SehirAd = "ÇANKIRI" },
new Sehir() { SehirAd = "ÇORUM" },
new Sehir() { SehirAd = "DENİZLİ" },
new Sehir() { SehirAd = "DİYARBAKIR" },
new Sehir() { SehirAd = "EDİRNE" },
new Sehir() { SehirAd = "ELAZIĞ" },
new Sehir() { SehirAd = "ERZİNCAN" },
new Sehir() { SehirAd = "ERZURUM" },
new Sehir() { SehirAd = "ESKİŞEHİR" },
new Sehir() { SehirAd = "GAZİANTEP" },
new Sehir() { SehirAd = "GİRESUN" },
new Sehir() { SehirAd = "GÜMÜŞHANE" },
new Sehir() { SehirAd = "HAKKARİ" },
new Sehir() { SehirAd = "HATAY" },
new Sehir() { SehirAd = "ISPARTA" },
new Sehir() { SehirAd = "İÇEL" },
new Sehir() { SehirAd = "İSTANBUL" },
new Sehir() { SehirAd = "İZMİR" },
new Sehir() { SehirAd = "KARS" },
new Sehir() { SehirAd = "KASTAMONU" },
new Sehir() { SehirAd = "KAYSERİ" },
new Sehir() { SehirAd = "KIRKLARELİ" },
new Sehir() { SehirAd = "KIRŞEHİR" },
new Sehir() { SehirAd = "KOCAELİ" },
new Sehir() { SehirAd = "KONYA" },
new Sehir() { SehirAd = "KÜTAHYA" },
new Sehir() { SehirAd = "MALATYA" },
new Sehir() { SehirAd = "MARAŞ" },
new Sehir() { SehirAd = "MANİSA" },
new Sehir() { SehirAd = "MARDİN" },
new Sehir() { SehirAd = "MUĞLA" },
new Sehir() { SehirAd = "MUŞ" },
new Sehir() { SehirAd = "NEVŞEHİR" },
new Sehir() { SehirAd = "NİĞDE" },
new Sehir() { SehirAd = "ORDU" },
new Sehir() { SehirAd = "RİZE" },
new Sehir() { SehirAd = "SAKARYA" },
new Sehir() { SehirAd = "SAMSUN" },
new Sehir() { SehirAd = "SİİRT" },
new Sehir() { SehirAd = "SİNOP" },
new Sehir() { SehirAd = "SİVAS" },
new Sehir() { SehirAd = "TEKİRDAĞ" },
new Sehir() { SehirAd = "TOKAT" },
new Sehir() { SehirAd = "TRABZON" },
new Sehir() { SehirAd = "TUNCELİ" },
new Sehir() { SehirAd = "ŞANLIURFA" },
new Sehir() { SehirAd = "UŞAK" },
new Sehir() { SehirAd = "VAN" },
new Sehir() { SehirAd = "YOZGAT" },
new Sehir() { SehirAd = "ZONGULDAK" },
new Sehir() { SehirAd = "AKSARAY" },
new Sehir() { SehirAd = "BAYBURT" },
new Sehir() { SehirAd = "KARAMAN" },
new Sehir() { SehirAd = "KIRIKKALE" },
new Sehir() { SehirAd = "BATMAN" },
new Sehir() { SehirAd = "ŞIRNAK" },
new Sehir() { SehirAd = "BARTIN" },
new Sehir() { SehirAd = "ARDAHAN" },
new Sehir() { SehirAd = "IĞDIR" },
new Sehir() { SehirAd = "YALOVA" },
new Sehir() { SehirAd = "KARABÜK" },
new Sehir() { SehirAd = "KİLİS" },
new Sehir() { SehirAd = "OSMANİYE" },
new Sehir() { SehirAd = "DÜZCE" }

            };
            foreach (var item in sehir)
            {
                context.Sehirs.Add(item);
            }
            context.SaveChanges();
            var semt = new List<Semt>()
            {

                new Semt() { SemtAd = "ÇUKUROVA", SehirId = 1 },
                new Semt() { SemtAd = "SARIÇAM", SehirId = 1 },
                new Semt() { SemtAd = "SEYHAN", SehirId = 1 },
                new Semt() { SemtAd = "ALADAĞ", SehirId = 1 },
                new Semt() { SemtAd = "CEYHAN", SehirId = 1 },
                new Semt() { SemtAd = "FEKE", SehirId = 1 },
                new Semt() { SemtAd = "İMAMOĞLU", SehirId = 1 },
                new Semt() { SemtAd = "KARAİSALI", SehirId = 1 },
                new Semt() { SemtAd = "KARATAŞ", SehirId = 1 },
                new Semt() { SemtAd = "KOZAN", SehirId = 1 },
                new Semt() { SemtAd = "POZANTI", SehirId = 1 },
                new Semt() { SemtAd = "SAİMBEYLİ", SehirId = 1 },
                new Semt() { SemtAd = "TUFANBEYLİ", SehirId = 1 },
                new Semt() { SemtAd = "YUMURTALIK", SehirId = 1 },
                new Semt() { SemtAd = "YÜREĞİR", SehirId = 1 },
                new Semt() { SemtAd = "BESNİ", SehirId = 2 },
                new Semt() { SemtAd = "ÇELİKHAN", SehirId = 2 },
                new Semt() { SemtAd = "GERGER", SehirId = 2 },
                new Semt() { SemtAd = "GÖLBAŞI", SehirId = 2 },
                new Semt() { SemtAd = "KAHTA", SehirId = 2 },
                new Semt() { SemtAd = "MERKEZ", SehirId = 2 },
                new Semt() { SemtAd = "SAMSAT", SehirId = 2 },
                new Semt() { SemtAd = "SİNCİK", SehirId = 2 },
                new Semt() { SemtAd = "TUT", SehirId = 2 },
                new Semt() { SemtAd = "BAŞMAKÇI", SehirId = 3 },
                new Semt() { SemtAd = "BAYAT", SehirId = 3 },
                new Semt() { SemtAd = "BOLVADİN", SehirId = 3 },
                new Semt() { SemtAd = "ÇAY", SehirId = 3 },
                new Semt() { SemtAd = "ÇOBANLAR", SehirId = 3 },
                new Semt() { SemtAd = "DAZKIRI", SehirId = 3 },
                new Semt() { SemtAd = "DİNAR", SehirId = 3 },
                new Semt() { SemtAd = "EMİRDAĞ", SehirId = 3 },
                new Semt() { SemtAd = "EVCİLER", SehirId = 3 },
                new Semt() { SemtAd = "HOCALAR", SehirId = 3 },
                new Semt() { SemtAd = "İHSANİYE", SehirId = 3 },
                new Semt() { SemtAd = "İSCEHİSAR", SehirId = 3 },
                new Semt() { SemtAd = "KIZILÖREN", SehirId = 3 },
                new Semt() { SemtAd = "SANDIKLI", SehirId = 3 },
                new Semt() { SemtAd = "SİNANPAŞA", SehirId = 3 },
                new Semt() { SemtAd = "SULTANDAĞI", SehirId = 3 },
                new Semt() { SemtAd = "ŞUHUT", SehirId = 3 },
                new Semt() { SemtAd = "DİYADİN", SehirId = 4 },
                new Semt() { SemtAd = "DOĞUBAYAZIT", SehirId = 4 },
                new Semt() { SemtAd = "ELEŞKİRT", SehirId = 4 },
                new Semt() { SemtAd = "HAMUR", SehirId = 4 },
                new Semt() { SemtAd = "PATNOS", SehirId = 4 },
                new Semt() { SemtAd = "TAŞLIÇAY", SehirId = 4 },
                new Semt() { SemtAd = "TUTAK", SehirId = 4 },
                new Semt() { SemtAd = "MERKEZ", SehirId = 5 },
                new Semt() { SemtAd = "GÖYNÜCEK", SehirId = 5 },
                new Semt() { SemtAd = "GÜMÜŞHACIKÖY", SehirId = 5 },
                new Semt() { SemtAd = "HAMAMÖZÜ", SehirId = 5 },
                new Semt() { SemtAd = "MERZİFON", SehirId = 5 },
                new Semt() { SemtAd = "SULUOVA", SehirId = 5 },
                new Semt() { SemtAd = "TAŞOVA", SehirId = 5 },
                new Semt() { SemtAd = "AKYURT", SehirId = 6 },
                new Semt() { SemtAd = "ALTINDAĞ", SehirId = 6 },
                new Semt() { SemtAd = "AYAŞ", SehirId = 6 },
                new Semt() { SemtAd = "BALA", SehirId = 6 },
                new Semt() { SemtAd = "BEYPAZARI", SehirId = 6 },
                new Semt() { SemtAd = "ÇAMLIDERE", SehirId = 6 },
                new Semt() { SemtAd = "ÇANKAYA", SehirId = 6 },
                new Semt() { SemtAd = "ÇUBUK", SehirId = 6 },
                new Semt() { SemtAd = "ELMADAĞ", SehirId = 6 },
                new Semt() { SemtAd = "ETİMESGUT", SehirId = 6 },
                new Semt() { SemtAd = "EVREN", SehirId = 6 },
                new Semt() { SemtAd = "GÖLBAŞI", SehirId = 6 },
                new Semt() { SemtAd = "GÜDÜL", SehirId = 6 },
                new Semt() { SemtAd = "HAYMANA", SehirId = 6 },
                new Semt() { SemtAd = "KAHRAMANKAZAN", SehirId = 6 },
                new Semt() { SemtAd = "KALECİK", SehirId = 6 },
                new Semt() { SemtAd = "KEÇİÖREN", SehirId = 6 },
                new Semt() { SemtAd = "KIZILCAHAMAM", SehirId = 6 },
                new Semt() { SemtAd = "MAMAK", SehirId = 6 },
                new Semt() { SemtAd = "NALLIHAN", SehirId = 6 },
                new Semt() { SemtAd = "POLATLI", SehirId = 6 },
                new Semt() { SemtAd = "PURSAKLAR", SehirId = 6 },
                new Semt() { SemtAd = "SİNCAN", SehirId = 6 },
                new Semt() { SemtAd = "ŞEREFLİKOÇHİSAR", SehirId = 6 },
                new Semt() { SemtAd = "YENİMAHALLE", SehirId = 6 },
                new Semt() { SemtAd = "AKSEKİ", SehirId = 7 },
                new Semt() { SemtAd = "AKSU", SehirId = 7 },
                new Semt() { SemtAd = "ALANYA", SehirId = 7 },
                new Semt() { SemtAd = "DEMRE", SehirId = 7 },
                new Semt() { SemtAd = "DÖŞEMEALTI", SehirId = 7 },
                new Semt() { SemtAd = "ELMALI", SehirId = 7 },
                new Semt() { SemtAd = "FİNİKE", SehirId = 7 },
                new Semt() { SemtAd = "GAZİPAŞA", SehirId = 7 },
                new Semt() { SemtAd = "GÜNDOĞMUŞ", SehirId = 7 },
                new Semt() { SemtAd = "İBRADI", SehirId = 7 },
                new Semt() { SemtAd = "KAŞ", SehirId = 7 },
                new Semt() { SemtAd = "KEMER", SehirId = 7 },
                new Semt() { SemtAd = "KEPEZ", SehirId = 7 },
                new Semt() { SemtAd = "KONYAALTI", SehirId = 7 },
                new Semt() { SemtAd = "KORKUTELİ", SehirId = 7 },
                new Semt() { SemtAd = "KUMLUCA", SehirId = 7 },
                new Semt() { SemtAd = "MANAVGAT", SehirId = 7 },
                new Semt() { SemtAd = "MURATPAŞA", SehirId = 7 },
                new Semt() { SemtAd = "SERİK", SehirId = 7 },
                new Semt() { SemtAd = "ARDANUÇ", SehirId = 8 },
                new Semt() { SemtAd = "ARHAVİ", SehirId = 8 },
                new Semt() { SemtAd = "BORÇKA", SehirId = 8 },
                new Semt() { SemtAd = "HOPA", SehirId = 8 },
                new Semt() { SemtAd = "MERMERENKÖY", SehirId = 8 },
                new Semt() { SemtAd = "ŞAVŞAT", SehirId = 8 },
                new Semt() { SemtAd = "YUSUFELİ", SehirId = 8 },
                new Semt() { SemtAd = "BOZDOĞAN", SehirId = 9 },
                new Semt() { SemtAd = "BUHARKENT", SehirId = 9 },
                new Semt() { SemtAd = "ÇİNE", SehirId = 9 },
                new Semt() { SemtAd = "DİDİM", SehirId = 9 },
                new Semt() { SemtAd = "EFELER", SehirId = 9 },
                new Semt() { SemtAd = "GERMENCİK", SehirId = 9 },
                new Semt() { SemtAd = "İNCİRLİOVA", SehirId = 9 },
                new Semt() { SemtAd = "KARACASU", SehirId = 9 },
                new Semt() { SemtAd = "KARPUZLU", SehirId = 9 },
                new Semt() { SemtAd = "KOÇARLI", SehirId = 9 },
                new Semt() { SemtAd = "KÖŞK", SehirId = 9 },
                new Semt() { SemtAd = "KUŞADASI", SehirId = 9 },
                new Semt() { SemtAd = "KUYUCAK", SehirId = 9 },
                new Semt() { SemtAd = "NAZİLLİ", SehirId = 9 },
                new Semt() { SemtAd = "SÖKE", SehirId = 9 },
                new Semt() { SemtAd = "SULTANHİSAR", SehirId = 9 },
                new Semt() { SemtAd = "YENİPAZAR", SehirId = 9 },
                new Semt() { SemtAd = "ALTIEYLÜL", SehirId = 10 },
                new Semt() { SemtAd = "AYVALIK", SehirId = 10 },
                new Semt() { SemtAd = "BALYA", SehirId = 10 },
                new Semt() { SemtAd = "BANDIRMA", SehirId = 10 },
                new Semt() { SemtAd = "BİGADİÇ", SehirId = 10 },
                new Semt() { SemtAd = "BURHANİYE", SehirId = 10 },
                new Semt() { SemtAd = "DURSUNBEY", SehirId = 10 },
                new Semt() { SemtAd = "EDREMİT", SehirId = 10 },
                new Semt() { SemtAd = "ERDEK", SehirId = 10 },
                new Semt() { SemtAd = "GÖMEÇ", SehirId = 10 },
                new Semt() { SemtAd = "GÖNEN", SehirId = 10 },
                new Semt() { SemtAd = "HAVRAN", SehirId = 10 },
                new Semt() { SemtAd = "İVRİNDİ", SehirId = 10 },
                new Semt() { SemtAd = "KEPSUT", SehirId = 10 },
                new Semt() { SemtAd = "MANYAS", SehirId = 10 },
                new Semt() { SemtAd = "MARMARA", SehirId = 10 },
                new Semt() { SemtAd = "SAVAŞTEPE", SehirId = 10 },
                new Semt() { SemtAd = "SINDIRGI", SehirId = 10 },
                new Semt() { SemtAd = "SUSURLUK", SehirId = 10 },
                new Semt() { SemtAd = "BİLECİK MERKEZ", SehirId = 11 },
    new Semt() { SemtAd = "GÖLPAZARI", SehirId = 11 },
    new Semt() { SemtAd = "İNHİSAR", SehirId = 11 },
    new Semt() { SemtAd = "PAZARYERİ", SehirId = 11 },
    new Semt() { SemtAd = "SÖĞÜT", SehirId = 11 },
    new Semt() { SemtAd = "YENİPAZAR", SehirId = 11 },
    new Semt() { SemtAd = "ADAKLI", SehirId = 12 },
    new Semt() { SemtAd = "GENÇ", SehirId = 12 },
    new Semt() { SemtAd = "KARLIOVA", SehirId = 12 },
    new Semt() { SemtAd = "KIĞI", SehirId = 12 },
    new Semt() { SemtAd = "MERKEZ", SehirId = 12 },
    new Semt() { SemtAd = "SOLHAN", SehirId = 12 },
    new Semt() { SemtAd = "YAYLADERE", SehirId = 12 },
    new Semt() { SemtAd = "YEDİSU", SehirId = 12 },
    new Semt() { SemtAd = "ADİLCEVAZ", SehirId = 13 },
    new Semt() { SemtAd = "AHLAT", SehirId = 13 },
    new Semt() { SemtAd = "GÜROYMAK", SehirId = 13 },
    new Semt() { SemtAd = "HİZAN", SehirId = 13 },
    new Semt() { SemtAd = "MUTKİ", SehirId = 13 },
    new Semt() { SemtAd = "TATVAN", SehirId = 13 },
    new Semt() { SemtAd = "DÖRTDİVAN", SehirId = 14 },
    new Semt() { SemtAd = "GEREDE", SehirId = 14 },
    new Semt() { SemtAd = "GÖYNÜK", SehirId = 14 },
    new Semt() { SemtAd = "KIBRISCIK", SehirId = 14 },
    new Semt() { SemtAd = "MENGEN", SehirId = 14 },
    new Semt() { SemtAd = "MUDURNU", SehirId = 14 },
    new Semt() { SemtAd = "SEBEN", SehirId = 14 },
    new Semt() { SemtAd = "YENİÇAĞA", SehirId = 14 },
    new Semt() { SemtAd = "MERKEZ", SehirId = 14 },
    new Semt() { SemtAd = "AĞLASUN", SehirId = 15 },
    new Semt() { SemtAd = "ALTINYAYLA", SehirId = 15 },
    new Semt() { SemtAd = "BUCAK", SehirId = 15 },
    new Semt() { SemtAd = "ÇAVDIR", SehirId = 15 },
    new Semt() { SemtAd = "ÇELTİKÇİ", SehirId = 15 },
    new Semt() { SemtAd = "GÖLHİSAR", SehirId = 15 },
    new Semt() { SemtAd = "KARAMANLI", SehirId = 15 },
    new Semt() { SemtAd = "KEMER", SehirId = 15 },
    new Semt() { SemtAd = "TEFENNİ", SehirId = 15 },
    new Semt() { SemtAd = "YEŞİLOVA", SehirId = 15 },
    new Semt() { SemtAd = "MERKEZ", SehirId = 15 },
    new Semt() { SemtAd = "BÜYÜKORHAN", SehirId = 16 },
    new Semt() { SemtAd = "GEMLİK", SehirId = 16 },
    new Semt() { SemtAd = "İNEGÖL", SehirId = 16 },
    new Semt() { SemtAd = "İZNİK", SehirId = 16 },
    new Semt() { SemtAd = "KARACABEY", SehirId = 16 },
    new Semt() { SemtAd = "KELES", SehirId = 16 },
    new Semt() { SemtAd = "KESTEL", SehirId = 16 },
    new Semt() { SemtAd = "MUDANYA", SehirId = 16 },
    new Semt() { SemtAd = "MUSTAFAKEMALPAŞA", SehirId = 16 },
    new Semt() { SemtAd = "NİLÜFER", SehirId = 16 },
    new Semt() { SemtAd = "ORHANELİ", SehirId = 16 },
    new Semt() { SemtAd = "ORHANGAZİ", SehirId = 16 },
    new Semt() { SemtAd = "OSMANGAZİ", SehirId = 16 },
    new Semt() { SemtAd = "YENİŞEHİR", SehirId = 16 },
    new Semt() { SemtAd = "YILDIRIM", SehirId = 16 },
    new Semt() { SemtAd = "AYVACIK", SehirId = 17 },
    new Semt() { SemtAd = "BAYRAMİÇ", SehirId = 17 },
    new Semt() { SemtAd = "BİGA", SehirId = 17 },
    new Semt() { SemtAd = "BOZCAADA", SehirId = 17 },
    new Semt() { SemtAd = "ÇAN", SehirId = 17 },
    new Semt() { SemtAd = "ÇANAKKALE MERKEZ", SehirId = 17 },
    new Semt() { SemtAd = "ECEABAT", SehirId = 17 },
    new Semt() { SemtAd = "EZİNE", SehirId = 17 },
    new Semt() { SemtAd = "GELİBOLU", SehirId = 17 },
    new Semt() { SemtAd = "GÖKÇEADA", SehirId = 17 },
    new Semt() { SemtAd = "LAPSEKİ", SehirId = 17 },
    new Semt() { SemtAd = "YENİCE", SehirId = 17 },
    new Semt() { SemtAd = "ATKARACALAR", SehirId = 18 },
    new Semt() { SemtAd = "BAYRAMÖREN", SehirId = 18 },
    new Semt() { SemtAd = "ÇANKIRI MERKEZ", SehirId = 18 },
    new Semt() { SemtAd = "ÇERKEŞ", SehirId = 18 },
    new Semt() { SemtAd = "EFLANİ", SehirId = 18 },
    new Semt() { SemtAd = "ILGAZ", SehirId = 18 },
    new Semt() { SemtAd = "KIZILIRMAK", SehirId = 18 },
    new Semt() { SemtAd = "KORGUN", SehirId = 18 },
    new Semt() { SemtAd = "KURŞUNLU", SehirId = 18 },
    new Semt() { SemtAd = "ORTA", SehirId = 18 },
    new Semt() { SemtAd = "ŞABANÖZÜ", SehirId = 18 },
    new Semt() { SemtAd = "YAPRAKLI", SehirId = 18 },
    new Semt() { SemtAd = "ALACA", SehirId = 19 },
    new Semt() { SemtAd = "BAYAT", SehirId = 19 },
    new Semt() { SemtAd = "BOĞAZKALE", SehirId = 19 },
    new Semt() { SemtAd = "DODURGA", SehirId = 19 },
    new Semt() { SemtAd = "İSKİLİP", SehirId = 19 },
    new Semt() { SemtAd = "KARGI", SehirId = 19 },
    new Semt() { SemtAd = "LAÇİN", SehirId = 19 },
    new Semt() { SemtAd = "MECİTÖZÜ", SehirId = 19 },
    new Semt() { SemtAd = "OĞUZLAR", SehirId = 19 },
    new Semt() { SemtAd = "ORTAKÖY", SehirId = 19 },
    new Semt() { SemtAd = "OSMANCIK", SehirId = 19 },
    new Semt() { SemtAd = "SUNGURLU", SehirId = 19 },
    new Semt() { SemtAd = "UĞURLUDAĞ", SehirId = 19 },
    new Semt() { SemtAd = "MERKEZ", SehirId = 19 },
    new Semt() { SemtAd = "ACIPAYAM", SehirId = 20 },
    new Semt() { SemtAd = "BABADAĞ", SehirId = 20 },
    new Semt() { SemtAd = "BAKLAN", SehirId = 20 },
    new Semt() { SemtAd = "BEKİLLİ", SehirId = 20 },
    new Semt() { SemtAd = "BEYAĞAÇ", SehirId = 20 },
    new Semt() { SemtAd = "BOZKURT", SehirId = 20 },
    new Semt() { SemtAd = "BULDAN", SehirId = 20 },
    new Semt() { SemtAd = "ÇAL", SehirId = 20 },
    new Semt() { SemtAd = "ÇAMELİ", SehirId = 20 },
    new Semt() { SemtAd = "ÇARDAK", SehirId = 20 },
    new Semt() { SemtAd = "ÇİVRİL", SehirId = 20 },
    new Semt() { SemtAd = "GÜNEY", SehirId = 20 },
    new Semt() { SemtAd = "HONAZ", SehirId = 20 },
    new Semt() { SemtAd = "KALE", SehirId = 20 },
    new Semt() { SemtAd = "SARAYKÖY", SehirId = 20 },
    new Semt() { SemtAd = "SERİNHİSAR", SehirId = 20 },
    new Semt() { SemtAd = "TAVAS", SehirId = 20 },
    new Semt() { SemtAd = "MERKEZ", SehirId = 20 },
    new Semt() { SemtAd = "BAĞLAR", SehirId = 21 },
    new Semt() { SemtAd = "BİSMİL", SehirId = 21 },
    new Semt() { SemtAd = "ÇERMİK", SehirId = 21 },
    new Semt() { SemtAd = "ÇINAR", SehirId = 21 },
    new Semt() { SemtAd = "ÇÜNGÜŞ", SehirId = 21 },
    new Semt() { SemtAd = "DİCLE", SehirId = 21 },
    new Semt() { SemtAd = "EGİL", SehirId = 21 },
    new Semt() { SemtAd = "ERGANİ", SehirId = 21 },
    new Semt() { SemtAd = "HANİ", SehirId = 21 },
    new Semt() { SemtAd = "HAZRO", SehirId = 21 },
    new Semt() { SemtAd = "KAYAPINAR", SehirId = 21 },
    new Semt() { SemtAd = "KOCAKÖY", SehirId = 21 },
    new Semt() { SemtAd = "KULP", SehirId = 21 },
    new Semt() { SemtAd = "LİCE", SehirId = 21 },
    new Semt() { SemtAd = "SİLVAN", SehirId = 21 },
    new Semt() { SemtAd = "SUR", SehirId = 21 },
    new Semt() { SemtAd = "EDİRNE MERKEZ", SehirId = 22 },
    new Semt() { SemtAd = "ENEZ", SehirId = 22 },
    new Semt() { SemtAd = "HAVSA", SehirId = 22 },
    new Semt() { SemtAd = "İPSALA", SehirId = 22 },
    new Semt() { SemtAd = "KEŞAN", SehirId = 22 },
    new Semt() { SemtAd = "LALAPAŞA", SehirId = 22 },
    new Semt() { SemtAd = "MERİÇ", SehirId = 22 },
    new Semt() { SemtAd = "SÜLOĞLU", SehirId = 22 },
    new Semt() { SemtAd = "AĞIN", SehirId = 23 },
    new Semt() { SemtAd = "ALACAKAYA", SehirId = 23 },
    new Semt() { SemtAd = "ARICAK", SehirId = 23 },
    new Semt() { SemtAd = "BASKİL", SehirId = 23 },
    new Semt() { SemtAd = "KARAKOÇAN", SehirId = 23 },
    new Semt() { SemtAd = "KEBAN", SehirId = 23 },
    new Semt() { SemtAd = "KOVANCILAR", SehirId = 23 },
    new Semt() { SemtAd = "MADEN", SehirId = 23 },
    new Semt() { SemtAd = "PALU", SehirId = 23 },
    new Semt() { SemtAd = "SİVRİCE", SehirId = 23 },
    new Semt() { SemtAd = "MERKEZ", SehirId = 23 },
    new Semt() { SemtAd = "ÇAYIRLI", SehirId = 24 },
    new Semt() { SemtAd = "İLİÇ", SehirId = 24 },
    new Semt() { SemtAd = "KEMAH", SehirId = 24 },
    new Semt() { SemtAd = "KEMALİYE", SehirId = 24 },
    new Semt() { SemtAd = "OTLUKBELİ", SehirId = 24 },
    new Semt() { SemtAd = "REFAHİYE", SehirId = 24 },
    new Semt() { SemtAd = "TERCAN", SehirId = 24 },
    new Semt() { SemtAd = "ÜZÜMLÜ", SehirId = 24 },
    new Semt() { SemtAd = "MERKEZ", SehirId = 24 },
    new Semt() { SemtAd = "AZİZİYE", SehirId = 25 },
    new Semt() { SemtAd = "AŞKALE", SehirId = 25 },
    new Semt() { SemtAd = "ÇAT", SehirId = 25 },
    new Semt() { SemtAd = "HINIS", SehirId = 25 },
    new Semt() { SemtAd = "HORASAN", SehirId = 25 },
    new Semt() { SemtAd = "İSPİR", SehirId = 25 },
    new Semt() { SemtAd = "KARAÇOBAN", SehirId = 25 },
    new Semt() { SemtAd = "KARAYAZI", SehirId = 25 },
    new Semt() { SemtAd = "KÖPRÜKÖY", SehirId = 25 },
    new Semt() { SemtAd = "NARMAN", SehirId = 25 },
    new Semt() { SemtAd = "OLTU", SehirId = 25 },
    new Semt() { SemtAd = "OLUR", SehirId = 25 },
    new Semt() { SemtAd = "PALANDÖKEN", SehirId = 25 },
    new Semt() { SemtAd = "PASİNLER", SehirId = 25 },
    new Semt() { SemtAd = "PAZARYOLU", SehirId = 25 },
    new Semt() { SemtAd = "Pazaryolu", SehirId = 25 },
    new Semt() { SemtAd = "ŞENKAYA", SehirId = 25 },
    new Semt() { SemtAd = "TEKMAN", SehirId = 25 },
    new Semt() { SemtAd = "TORTUM", SehirId = 25 },
    new Semt() { SemtAd = "UZUNDERE", SehirId = 25 },
    new Semt() { SemtAd = "YAKUTİYE", SehirId = 25 },
    new Semt() { SemtAd = "ALPU", SehirId = 26 },
    new Semt() { SemtAd = "BEYLİKOVA", SehirId = 26 },
    new Semt() { SemtAd = "ÇİFTELER", SehirId = 26 },
    new Semt() { SemtAd = "GÜNYÜZÜ", SehirId = 26 },
    new Semt() { SemtAd = "HAN", SehirId = 26 },
    new Semt() { SemtAd = "İNÖNÜ", SehirId = 26 },
    new Semt() { SemtAd = "MAHMUDİYE", SehirId = 26 },
    new Semt() { SemtAd = "MİHALGAZİ", SehirId = 26 },
    new Semt() { SemtAd = "ODEON", SehirId = 26 },
    new Semt() { SemtAd = "SARICAKAYA", SehirId = 26 },
    new Semt() { SemtAd = "SEYİTGAZİ", SehirId = 26 },
    new Semt() { SemtAd = "SİVRİHİSAR", SehirId = 26 },
    new Semt() { SemtAd = "TEPEBAŞI", SehirId = 26 },
    new Semt() { SemtAd = "OĞUZELİ", SehirId = 27 },
    new Semt() { SemtAd = "YAVUZELİ", SehirId = 27 },
    new Semt() { SemtAd = "ŞAHİNBEY", SehirId = 27 },
    new Semt() { SemtAd = "ŞEHİTKAMİL", SehirId = 27 },
    new Semt() { SemtAd = "OĞUZELİ", SehirId = 27 },
    new Semt() { SemtAd = "KARKAMIŞ", SehirId = 27 },
    new Semt() { SemtAd = "ARABAN", SehirId = 27 },
    new Semt() { SemtAd = "YILDIZELİ", SehirId = 27 },
    new Semt() { SemtAd = "NİZİP", SehirId = 27 },
    new Semt() { SemtAd = "ALUCRA", SehirId = 28 },
    new Semt() { SemtAd = "BULANCAK", SehirId = 28 },
    new Semt() { SemtAd = "ÇAMOLUK", SehirId = 28 },
    new Semt() { SemtAd = "ÇANAKÇI", SehirId = 28 },
    new Semt() { SemtAd = "DERELİ", SehirId = 28 },
    new Semt() { SemtAd = "DOĞANKENT", SehirId = 28 },
    new Semt() { SemtAd = "ESPİYE", SehirId = 28 },
    new Semt() { SemtAd = "EYNESİL", SehirId = 28 },
    new Semt() { SemtAd = "GÖRELE", SehirId = 28 },
    new Semt() { SemtAd = "GÜCE", SehirId = 28 },
    new Semt() { SemtAd = "KEŞAP", SehirId = 28 },
    new Semt() { SemtAd = "PİRAZİZ", SehirId = 28 },
    new Semt() { SemtAd = "ŞEBİNKARAHİSAR", SehirId = 28 },
    new Semt() { SemtAd = "TİREBOLU", SehirId = 28 },
    new Semt() { SemtAd = "YAĞLIDERE", SehirId = 28 },
    new Semt() { SemtAd = "MERKEZ", SehirId = 28 },
    new Semt() { SemtAd = "KELKİT", SehirId = 29 },
    new Semt() { SemtAd = "KÖSE", SehirId = 29 },
    new Semt() { SemtAd = "KÜRTÜN", SehirId = 29 },
    new Semt() { SemtAd = "ŞİRAN", SehirId = 29 },
    new Semt() { SemtAd = "TORUL", SehirId = 29 },
    new Semt() { SemtAd = "ÇUKURCA", SehirId = 30 },
    new Semt() { SemtAd = "HAKKARİ", SehirId = 30 },
    new Semt() { SemtAd = "ŞEMDİNLİ", SehirId = 30 },
    new Semt() { SemtAd = "YÜKSEKOVA", SehirId = 30 },
    new Semt() { SemtAd = "ALTINÖZÜ", SehirId = 31 },
    new Semt() { SemtAd = "ANTAKYA", SehirId = 31 },
    new Semt() { SemtAd = "ARSUZ", SehirId = 31 },
    new Semt() { SemtAd = "BELEN", SehirId = 31 },
    new Semt() { SemtAd = "DEFNE", SehirId = 31 },
    new Semt() { SemtAd = "DÖRTYOL", SehirId = 31 },
    new Semt() { SemtAd = "ERZİN", SehirId = 31 },
    new Semt() { SemtAd = "HASSA", SehirId = 31 },
    new Semt() { SemtAd = "İSKENDERUN", SehirId = 31 },
    new Semt() { SemtAd = "KIRIKHAN", SehirId = 31 },
    new Semt() { SemtAd = "KUMLUCA", SehirId = 31 },
    new Semt() { SemtAd = "PAYAS", SehirId = 31 },
    new Semt() { SemtAd = "REYHANLI", SehirId = 31 },
    new Semt() { SemtAd = "SAMANDAĞ", SehirId = 31 },
    new Semt() { SemtAd = "AKSU", SehirId = 32 },
    new Semt() { SemtAd = "ATABEY", SehirId = 32 },
    new Semt() { SemtAd = "EĞİRDİR", SehirId = 32 },
    new Semt() { SemtAd = "GELENDOST", SehirId = 32 },
    new Semt() { SemtAd = "GÖNEN", SehirId = 32 },
    new Semt() { SemtAd = "ISPARTA", SehirId = 32 },
    new Semt() { SemtAd = "KEÇİBORLU", SehirId = 32 },
    new Semt() { SemtAd = "SENİRKENT", SehirId = 32 },
    new Semt() { SemtAd = "SÜTÇÜLER", SehirId = 32 },
    new Semt() { SemtAd = "ŞARKİKARAAĞAÇ", SehirId = 32 },
    new Semt() { SemtAd = "ULUBORLU", SehirId = 32 },
    new Semt() { SemtAd = "YALVAÇ", SehirId = 32 },
    new Semt() { SemtAd = "YENİŞARBADEMLİ", SehirId = 32 },
    new Semt() { SemtAd = "AKDENİZ", SehirId = 33 },
    new Semt() { SemtAd = "ANAMUR", SehirId = 33 },
    new Semt() { SemtAd = "AYDINCIK", SehirId = 33 },
    new Semt() { SemtAd = "BOZYAZI", SehirId = 33 },
    new Semt() { SemtAd = "ÇAMLIYAYLA", SehirId = 33 },
    new Semt() { SemtAd = "ERDEMLİ", SehirId = 33 },
    new Semt() { SemtAd = "GÜLNAR", SehirId = 33 },
    new Semt() { SemtAd = "MEZİTLİ", SehirId = 33 },
    new Semt() { SemtAd = "MUT", SehirId = 33 },
    new Semt() { SemtAd = "SİLİFKE", SehirId = 33 },
    new Semt() { SemtAd = "TARSUS", SehirId = 33 },
    new Semt() { SemtAd = "TOROSLAR", SehirId = 33 },
    new Semt() { SemtAd = "YENİŞEHİR", SehirId = 33 },
    new Semt() { SemtAd = "ADALAR", SehirId = 34 },
    new Semt() { SemtAd = "ARNAVUTKÖY", SehirId = 34 },
    new Semt() { SemtAd = "ATAŞEHİR", SehirId = 34 },
    new Semt() { SemtAd = "AVCILAR", SehirId = 34 },
    new Semt() { SemtAd = "BAĞCILAR", SehirId = 34 },
    new Semt() { SemtAd = "BAHÇELİEVLER", SehirId = 34 },
    new Semt() { SemtAd = "BAKIRKÖY", SehirId = 34 },
    new Semt() { SemtAd = "BAŞAKŞEHİR", SehirId = 34 },
    new Semt() { SemtAd = "BAYRAMPAŞA", SehirId = 34 },
    new Semt() { SemtAd = "BEŞİKTAŞ", SehirId = 34 },
    new Semt() { SemtAd = "BEYKOZ", SehirId = 34 },
    new Semt() { SemtAd = "BEYLİKDÜZÜ", SehirId = 34 },
    new Semt() { SemtAd = "BEYOĞLU", SehirId = 34 },
    new Semt() { SemtAd = "BÜYÜKÇEKMECE", SehirId = 34 },
    new Semt() { SemtAd = "ÇATALCA", SehirId = 34 },
    new Semt() { SemtAd = "ÇEKMEKÖY", SehirId = 34 },
    new Semt() { SemtAd = "ESENLER", SehirId = 34 },
    new Semt() { SemtAd = "ESENYURT", SehirId = 34 },
    new Semt() { SemtAd = "EYÜPSULTAN", SehirId = 34 },
    new Semt() { SemtAd = "FATİH", SehirId = 34 },
    new Semt() { SemtAd = "GAZİOSMANPAŞA", SehirId = 34 },
    new Semt() { SemtAd = "GÜNGÖREN", SehirId = 34 },
    new Semt() { SemtAd = "KADIKÖY", SehirId = 34 },
    new Semt() { SemtAd = "KAĞITHANE", SehirId = 34 },
    new Semt() { SemtAd = "KARTAL", SehirId = 34 },
    new Semt() { SemtAd = "KÜÇÜKÇEKMECE", SehirId = 34 },
    new Semt() { SemtAd = "MALTEPE", SehirId = 34 },
    new Semt() { SemtAd = "PENDİK", SehirId = 34 },
    new Semt() { SemtAd = "SANCAKTEPE", SehirId = 34 },
    new Semt() { SemtAd = "SARIYER", SehirId = 34 },
    new Semt() { SemtAd = "SİLİVRİ", SehirId = 34 },
    new Semt() { SemtAd = "SULTANBEYLİ", SehirId = 34 },
    new Semt() { SemtAd = "SULTANGAZİ", SehirId = 34 },
    new Semt() { SemtAd = "ŞİLE", SehirId = 34 },
    new Semt() { SemtAd = "ŞİŞLİ", SehirId = 34 },
    new Semt() { SemtAd = "TUZLA", SehirId = 34 },
    new Semt() { SemtAd = "ÜMRANİYE", SehirId = 34 },
    new Semt() { SemtAd = "ÜSKÜDAR", SehirId = 34 },
    new Semt() { SemtAd = "ZEYTİNBURNU", SehirId = 34 },
    new Semt() { SemtAd = "ALİAĞA", SehirId = 35 },
    new Semt() { SemtAd = "BALÇOVA", SehirId = 35 },
    new Semt() { SemtAd = "BAYINDIR", SehirId = 35 },
    new Semt() { SemtAd = "BAYRAKLI", SehirId = 35 },
    new Semt() { SemtAd = "BERGAMA", SehirId = 35 },
    new Semt() { SemtAd = "BEYDAĞ", SehirId = 35 },
    new Semt() { SemtAd = "BORNOVA", SehirId = 35 },
    new Semt() { SemtAd = "BUCA", SehirId = 35 },
    new Semt() { SemtAd = "ÇEŞME", SehirId = 35 },
    new Semt() { SemtAd = "ÇİĞLİ", SehirId = 35 },
    new Semt() { SemtAd = "DİKİLİ", SehirId = 35 },
    new Semt() { SemtAd = "FOÇA", SehirId = 35 },
    new Semt() { SemtAd = "GAZİEMİR", SehirId = 35 },
    new Semt() { SemtAd = "GÜZELBAHÇE", SehirId = 35 },
    new Semt() { SemtAd = "KARABAĞLAR", SehirId = 35 },
    new Semt() { SemtAd = "KARABURUN", SehirId = 35 },
    new Semt() { SemtAd = "KARŞIYAKA", SehirId = 35 },
    new Semt() { SemtAd = "KEMALPAŞA", SehirId = 35 },
    new Semt() { SemtAd = "KINIK", SehirId = 35 },
    new Semt() { SemtAd = "KİRAZ", SehirId = 35 },
    new Semt() { SemtAd = "KONAK", SehirId = 35 },
    new Semt() { SemtAd = "MENDERES", SehirId = 35 },
    new Semt() { SemtAd = "MENEMEN", SehirId = 35 },
    new Semt() { SemtAd = "NARLIDERE", SehirId = 35 },
    new Semt() { SemtAd = "ÖDEMİŞ", SehirId = 35 },
    new Semt() { SemtAd = "SEFERİHİSAR", SehirId = 35 },
    new Semt() { SemtAd = "SELÇUK", SehirId = 35 },
    new Semt() { SemtAd = "TİRE", SehirId = 35 },
    new Semt() { SemtAd = "TORBALI", SehirId = 35 },
    new Semt() { SemtAd = "URLA", SehirId = 35 },
     new Semt() { SemtAd = "AKYAKA", SehirId = 36 },
    new Semt() { SemtAd = "ARPAÇAY", SehirId = 36 },
    new Semt() { SemtAd = "DİGOR", SehirId = 36 },
    new Semt() { SemtAd = "KAĞIZMAN", SehirId = 36 },
    new Semt() { SemtAd = "KARS", SehirId = 36 },
    new Semt() { SemtAd = "SELİM", SehirId = 36 },
    new Semt() { SemtAd = "SARIKAMIŞ", SehirId = 36 },
    new Semt() { SemtAd = "SUSUZ", SehirId = 36 },
    new Semt() { SemtAd = "ABANA", SehirId = 37 },
    new Semt() { SemtAd = "AĞLI", SehirId = 37 },
    new Semt() { SemtAd = "ARAÇ", SehirId = 37 },
    new Semt() { SemtAd = "AZDAVAY", SehirId = 37 },
    new Semt() { SemtAd = "BOZKURT", SehirId = 37 },
    new Semt() { SemtAd = "CİDE", SehirId = 37 },
    new Semt() { SemtAd = "DADAY", SehirId = 37 },
    new Semt() { SemtAd = "DEVREKANİ", SehirId = 37 },
    new Semt() { SemtAd = "DOĞANHİSAR", SehirId = 37 },
    new Semt() { SemtAd = "HANÖNÜ", SehirId = 37 },
    new Semt() { SemtAd = "İHSANGAZİ", SehirId = 37 },
    new Semt() { SemtAd = "İNEBOLU", SehirId = 37 },
    new Semt() { SemtAd = "KÜRE", SehirId = 37 },
    new Semt() { SemtAd = "PINARBAŞI", SehirId = 37 },
    new Semt() { SemtAd = "SEYDİLER", SehirId = 37 },
    new Semt() { SemtAd = "ŞENPAZAR", SehirId = 37 },
    new Semt() { SemtAd = "TAŞKÖPRÜ", SehirId = 37 },
    new Semt() { SemtAd = "TOSYA", SehirId = 37 },
    new Semt() { SemtAd = "AKKIŞLA", SehirId = 38 },
    new Semt() { SemtAd = "BÜNYAN", SehirId = 38 },
    new Semt() { SemtAd = "DEVELİ", SehirId = 38 },
    new Semt() { SemtAd = "FELAHİYE", SehirId = 38 },
    new Semt() { SemtAd = "HACILAR", SehirId = 38 },
    new Semt() { SemtAd = "İNCESU", SehirId = 38 },
    new Semt() { SemtAd = "KOCASİNAN", SehirId = 38 },
    new Semt() { SemtAd = "MELİKGAZİ", SehirId = 38 },
    new Semt() { SemtAd = "ÖZVATAN", SehirId = 38 },
    new Semt() { SemtAd = "SARIOĞLAN", SehirId = 38 },
    new Semt() { SemtAd = "SARIZ", SehirId = 38 },
    new Semt() { SemtAd = "TALAS", SehirId = 38 },
    new Semt() { SemtAd = "TOMARZA", SehirId = 38 },
    new Semt() { SemtAd = "YAHYALI", SehirId = 38 },
    new Semt() { SemtAd = "YEŞİLHİSAR", SehirId = 38 },
    new Semt() { SemtAd = "BABAESKİ", SehirId = 39 },
    new Semt() { SemtAd = "DEMİRKÖY", SehirId = 39 },
    new Semt() { SemtAd = "KIRKLARELİ", SehirId = 39 },
    new Semt() { SemtAd = "KOFÇAZ", SehirId = 39 },
    new Semt() { SemtAd = "LÜLEBURGAZ", SehirId = 39 },
    new Semt() { SemtAd = "PEHLİVANKÖY", SehirId = 39 },
    new Semt() { SemtAd = "PINARHİSAR", SehirId = 39 },
    new Semt() { SemtAd = "VİZE", SehirId = 39 },
    new Semt() { SemtAd = "AKÇAKENT", SehirId = 40 },
    new Semt() { SemtAd = "AKPINAR", SehirId = 40 },
    new Semt() { SemtAd = "BOZTEPE", SehirId = 40 },
    new Semt() { SemtAd = "ÇİÇEKDAĞI", SehirId = 40 },
    new Semt() { SemtAd = "KAMAN", SehirId = 40 },
    new Semt() { SemtAd = "KIRŞEHİR", SehirId = 40 },
    new Semt() { SemtAd = "MERKEZ", SehirId = 40 },
    new Semt() { SemtAd = "MUCUR", SehirId = 40 },
    new Semt() { SemtAd = "BAŞİSKELE", SehirId = 41 },
    new Semt() { SemtAd = "ÇAYIROVA", SehirId = 41 },
    new Semt() { SemtAd = "DARICA", SehirId = 41 },
    new Semt() { SemtAd = "DERİNCE", SehirId = 41 },
    new Semt() { SemtAd = "DİLOVASI", SehirId = 41 },
    new Semt() { SemtAd = "GEBZE", SehirId = 41 },
    new Semt() { SemtAd = "GÖLCÜK", SehirId = 41 },
    new Semt() { SemtAd = "İZMİT", SehirId = 41 },
    new Semt() { SemtAd = "KANDIRA", SehirId = 41 },
    new Semt() { SemtAd = "KARAMÜRSEL", SehirId = 41 },
    new Semt() { SemtAd = "KARTEPE", SehirId = 41 },
    new Semt() { SemtAd = "KÖRFEZ", SehirId = 41 },
    new Semt() { SemtAd = "AHIRLI", SehirId = 42 },
    new Semt() { SemtAd = "AKÖREN", SehirId = 42 },
    new Semt() { SemtAd = "AKŞEHİR", SehirId = 42 },
    new Semt() { SemtAd = "ALTINEKİN", SehirId = 42 },
    new Semt() { SemtAd = "BEYŞEHİR", SehirId = 42 },
    new Semt() { SemtAd = "BOZKIR", SehirId = 42 },
    new Semt() { SemtAd = "CİHANBEYLİ", SehirId = 42 },
    new Semt() { SemtAd = "ÇELTİK", SehirId = 42 },
    new Semt() { SemtAd = "ÇUMRA", SehirId = 42 },
    new Semt() { SemtAd = "DERBENT", SehirId = 42 },
    new Semt() { SemtAd = "DEREBUCAK", SehirId = 42 },
    new Semt() { SemtAd = "DOĞANHİSAR", SehirId = 42 },
    new Semt() { SemtAd = "EMİRGAZİ", SehirId = 42 },
    new Semt() { SemtAd = "EREĞLİ", SehirId = 42 },
    new Semt() { SemtAd = "GÜNEYSINIR", SehirId = 42 },
    new Semt() { SemtAd = "HADİM", SehirId = 42 },
    new Semt() { SemtAd = "HALKAPINAR", SehirId = 42 },
    new Semt() { SemtAd = "HÜYÜK", SehirId = 42 },
    new Semt() { SemtAd = "ILGIN", SehirId = 42 },
    new Semt() { SemtAd = "KADINHANI", SehirId = 42 },
    new Semt() { SemtAd = "KARAPINAR", SehirId = 42 },
    new Semt() { SemtAd = "KARATAY", SehirId = 42 },
    new Semt() { SemtAd = "KULU", SehirId = 42 },
    new Semt() { SemtAd = "MERAM", SehirId = 42 },
    new Semt() { SemtAd = "SARAYÖNÜ", SehirId = 42 },
    new Semt() { SemtAd = "SELÇUKLU", SehirId = 42 },
    new Semt() { SemtAd = "SEYDİŞEHİR", SehirId = 42 },
    new Semt() { SemtAd = "TAŞKENT", SehirId = 42 },
    new Semt() { SemtAd = "TUZLUKÇU", SehirId = 42 },
    new Semt() { SemtAd = "YALIHÜYÜK", SehirId = 42 },
    new Semt() { SemtAd = "YUNAK", SehirId = 42 },
    new Semt() { SemtAd = "ALTINTAŞ", SehirId = 43 },
    new Semt() { SemtAd = "ASYA", SehirId = 43 },
    new Semt() { SemtAd = "ÇAVDARHİSAR", SehirId = 43 },
    new Semt() { SemtAd = "DOMANİÇ", SehirId = 43 },
    new Semt() { SemtAd = "DUMLUPINAR", SehirId = 43 },
    new Semt() { SemtAd = "EMET", SehirId = 43 },
    new Semt() { SemtAd = "GEDİZ", SehirId = 43 },
    new Semt() { SemtAd = "HİSARCIK", SehirId = 43 },
    new Semt() { SemtAd = "KÜTAHYA", SehirId = 43 },
    new Semt() { SemtAd = "PAZARLAR", SehirId = 43 },
    new Semt() { SemtAd = "ŞAPHANE", SehirId = 43 },
    new Semt() { SemtAd = "SIMAV", SehirId = 43 },
    new Semt() { SemtAd = "TAVŞANLI", SehirId = 43 },
     new Semt() { SemtAd = "AKÇADAĞ", SehirId = 44 },
    new Semt() { SemtAd = "ARAPGİR", SehirId = 44 },
    new Semt() { SemtAd = "ARGUVAN", SehirId = 44 },
    new Semt() { SemtAd = "BATTALGAZİ", SehirId = 44 },
    new Semt() { SemtAd = "DARENDE", SehirId = 44 },
    new Semt() { SemtAd = "DOĞANŞEHİR", SehirId = 44 },
    new Semt() { SemtAd = "DOĞANYOL", SehirId = 44 },
    new Semt() { SemtAd = "HEKİMHAN", SehirId = 44 },
    new Semt() { SemtAd = "KALE", SehirId = 44 },
    new Semt() { SemtAd = "KULUNCAK", SehirId = 44 },
    new Semt() { SemtAd = "PÜTÜRGE", SehirId = 44 },
    new Semt() { SemtAd = "YEŞİLYURT", SehirId = 44 },
    new Semt() { SemtAd = "YEŞİLYURT", SehirId = 44 },
    new Semt() { SemtAd = "AKHİSAR", SehirId = 45 },
    new Semt() { SemtAd = "ALAŞEHİR", SehirId = 45 },
    new Semt() { SemtAd = "DEMİRCİ", SehirId = 45 },
    new Semt() { SemtAd = "GÖLMARMARA", SehirId = 45 },
    new Semt() { SemtAd = "GÖRDES", SehirId = 45 },
    new Semt() { SemtAd = "KIRKAĞAÇ", SehirId = 45 },
    new Semt() { SemtAd = "KÖPRÜBAŞI", SehirId = 45 },
    new Semt() { SemtAd = "KULA", SehirId = 45 },
    new Semt() { SemtAd = "MANİSA", SehirId = 45 },
    new Semt() { SemtAd = "SALİHLİ", SehirId = 45 },
    new Semt() { SemtAd = "SARIGÖL", SehirId = 45 },
    new Semt() { SemtAd = "SARUHANLI", SehirId = 45 },
    new Semt() { SemtAd = "SELENDİ", SehirId = 45 },
    new Semt() { SemtAd = "SOMA", SehirId = 45 },
    new Semt() { SemtAd = "TURGUTLU", SehirId = 45 },
    new Semt() { SemtAd = "AFŞİN", SehirId = 46 },
    new Semt() { SemtAd = "ANDIRIN", SehirId = 46 },
    new Semt() { SemtAd = "ÇAĞLAYANCERİT", SehirId = 46 },
    new Semt() { SemtAd = "DULKADİROĞLU", SehirId = 46 },
    new Semt() { SemtAd = "EKİNÖZÜ", SehirId = 46 },
    new Semt() { SemtAd = "ELBİSTAN", SehirId = 46 },
    new Semt() { SemtAd = "GÖKSUN", SehirId = 46 },
    new Semt() { SemtAd = "NURHAK", SehirId = 46 },
    new Semt() { SemtAd = "ONİKİŞUBAT", SehirId = 46 },
    new Semt() { SemtAd = "PAZARCIK", SehirId = 46 },
    new Semt() { SemtAd = "TÜRKOĞLU", SehirId = 46 },
    new Semt() { SemtAd = "ARTUKLU", SehirId = 47 },
    new Semt() { SemtAd = "DARGEÇİT", SehirId = 47 },
    new Semt() { SemtAd = "DERİK", SehirId = 47 },
    new Semt() { SemtAd = "KIZILTEPE", SehirId = 47 },
    new Semt() { SemtAd = "MAZIDAĞI", SehirId = 47 },
    new Semt() { SemtAd = "MİDYAT", SehirId = 47 },
    new Semt() { SemtAd = "NUSAYBİN", SehirId = 47 },
    new Semt() { SemtAd = "ÖMERLİ", SehirId = 47 },
    new Semt() { SemtAd = "SAVUR", SehirId = 47 },
    new Semt() { SemtAd = "YEŞİLLİ", SehirId = 47 },
    new Semt() { SemtAd = "BODRUM", SehirId = 48 },
    new Semt() { SemtAd = "DALAMAN", SehirId = 48 },
    new Semt() { SemtAd = "DATÇA", SehirId = 48 },
    new Semt() { SemtAd = "FETHİYE", SehirId = 48 },
    new Semt() { SemtAd = "KAVAKLIDERE", SehirId = 48 },
    new Semt() { SemtAd = "KÖYCEĞİZ", SehirId = 48 },
    new Semt() { SemtAd = "MARMARİS", SehirId = 48 },
    new Semt() { SemtAd = "MENTEŞE", SehirId = 48 },
    new Semt() { SemtAd = "MİLAS", SehirId = 48 },
    new Semt() { SemtAd = "ORTACA", SehirId = 48 },
    new Semt() { SemtAd = "SEYDİKEMER", SehirId = 48 },
    new Semt() { SemtAd = "ULA", SehirId = 48 },
    new Semt() { SemtAd = "YATAĞAN", SehirId = 48 },
    new Semt() { SemtAd = "BULANIK", SehirId = 49 },
    new Semt() { SemtAd = "HASKÖY", SehirId = 49 },
    new Semt() { SemtAd = "KORKUT", SehirId = 49 },
    new Semt() { SemtAd = "MALAZGİRT", SehirId = 49 },
    new Semt() { SemtAd = "MERKEZ", SehirId = 49 },
    new Semt() { SemtAd = "VARTO", SehirId = 49 },
     new Semt() { SemtAd = "ACIGÖL", SehirId = 50 },
    new Semt() { SemtAd = "AVANOS", SehirId = 50 },
    new Semt() { SemtAd = "DERİNKUYU", SehirId = 50 },
    new Semt() { SemtAd = "GÜLŞEHİR", SehirId = 50 },
    new Semt() { SemtAd = "HACIBEKTAŞ", SehirId = 50 },
    new Semt() { SemtAd = "KOZAKLI", SehirId = 50 },
    new Semt() { SemtAd = "NEVŞEHİR", SehirId = 50 },
    new Semt() { SemtAd = "ÜRGÜP", SehirId = 50 },
     new Semt() { SemtAd = "ALTUNHİSAR", SehirId = 51 },
    new Semt() { SemtAd = "BOR", SehirId = 51 },
    new Semt() { SemtAd = "ÇAMARDI", SehirId = 51 },
    new Semt() { SemtAd = "ÇİFTLİK", SehirId = 51 },
    new Semt() { SemtAd = "ULUKIŞLA", SehirId = 51 },
    new Semt() { SemtAd = "AKKUŞ", SehirId = 52 },
    new Semt() { SemtAd = "ALTINORDU", SehirId = 52 },
    new Semt() { SemtAd = "AYBASTI", SehirId = 52 },
    new Semt() { SemtAd = "ÇAMAŞ", SehirId = 52 },
    new Semt() { SemtAd = "ÇATALPINAR", SehirId = 52 },
    new Semt() { SemtAd = "ÇAYBAŞI", SehirId = 52 },
    new Semt() { SemtAd = "FATSA", SehirId = 52 },
    new Semt() { SemtAd = "GÖLKÖY", SehirId = 52 },
    new Semt() { SemtAd = "GÜLYALI", SehirId = 52 },
    new Semt() { SemtAd = "GÜRGENTEPE", SehirId = 52 },
    new Semt() { SemtAd = "İKİZCE", SehirId = 52 },
    new Semt() { SemtAd = "KABADÜZ", SehirId = 52 },
    new Semt() { SemtAd = "KABATAŞ", SehirId = 52 },
    new Semt() { SemtAd = "KORGAN", SehirId = 52 },
    new Semt() { SemtAd = "KUMRU", SehirId = 52 },
    new Semt() { SemtAd = "MESUDİYE", SehirId = 52 },
    new Semt() { SemtAd = "PERŞEMBE", SehirId = 52 },
    new Semt() { SemtAd = "ULUBEY", SehirId = 52 },
    new Semt() { SemtAd = "ÜNYE", SehirId = 52 },
    new Semt() { SemtAd = "ARDANUÇ", SehirId = 53 },
    new Semt() { SemtAd = "ARDEŞEN", SehirId = 53 },
    new Semt() { SemtAd = "ÇAMLIHEMŞİN", SehirId = 53 },
    new Semt() { SemtAd = "ÇAYELİ", SehirId = 53 },
    new Semt() { SemtAd = "DEREPAZARI", SehirId = 53 },
    new Semt() { SemtAd = "FINDIKLI", SehirId = 53 },
    new Semt() { SemtAd = "GÜNEYSU", SehirId = 53 },
    new Semt() { SemtAd = "HEMŞİN", SehirId = 53 },
    new Semt() { SemtAd = "İKİZDERE", SehirId = 53 },
    new Semt() { SemtAd = "İYİDERE", SehirId = 53 },
    new Semt() { SemtAd = "KALKANDERE", SehirId = 53 },
    new Semt() { SemtAd = "MERKEZ", SehirId = 53 },
     new Semt() { SemtAd = "ADIYAMAN", SehirId = 54 },
    new Semt() { SemtAd = "ATKARACALAR", SehirId = 54 },
    new Semt() { SemtAd = "AYVASIL", SehirId = 54 },
    new Semt() { SemtAd = "FERİZLİ", SehirId = 54 },
    new Semt() { SemtAd = "GEYVE", SehirId = 54 },
    new Semt() { SemtAd = "HENDEK", SehirId = 54 },
    new Semt() { SemtAd = "KARAPÜRÇEK", SehirId = 54 },
    new Semt() { SemtAd = "KARASU", SehirId = 54 },
    new Semt() { SemtAd = "KAYNARCA", SehirId = 54 },
    new Semt() { SemtAd = "KOCAALİ", SehirId = 54 },
    new Semt() { SemtAd = "PAMUKOVA", SehirId = 54 },
    new Semt() { SemtAd = "SAPANCA", SehirId = 54 },
    new Semt() { SemtAd = "SERDİVAN", SehirId = 54 },
    new Semt() { SemtAd = "SÖĞÜTLÜ", SehirId = 54 },
    new Semt() { SemtAd = "TARAKLI", SehirId = 54 },
     new Semt() { SemtAd = "ALAÇAM", SehirId = 55 },
    new Semt() { SemtAd = "ASARCIK", SehirId = 55 },
    new Semt() { SemtAd = "ATAKUM", SehirId = 55 },
    new Semt() { SemtAd = "AYVACIK", SehirId = 55 },
    new Semt() { SemtAd = "BAFRA", SehirId = 55 },
    new Semt() { SemtAd = "CANİK", SehirId = 55 },
    new Semt() { SemtAd = "ÇARŞAMBA", SehirId = 55 },
    new Semt() { SemtAd = "HAVZA", SehirId = 55 },
    new Semt() { SemtAd = "İLKADIM", SehirId = 55 },
    new Semt() { SemtAd = "KAVAK", SehirId = 55 },
    new Semt() { SemtAd = "LADİK", SehirId = 55 },
    new Semt() { SemtAd = "OĞUZELİ", SehirId = 55 },
    new Semt() { SemtAd = "SALIPAZARI", SehirId = 55 },
    new Semt() { SemtAd = "TEKKEKÖY", SehirId = 55 },
    new Semt() { SemtAd = "TERME", SehirId = 55 },
    new Semt() { SemtAd = "VAKFIKEBİR", SehirId = 55 },
    new Semt() { SemtAd = "YAKAKENT", SehirId = 55 },
     new Semt() { SemtAd = "BAYKAN", SehirId = 56 },
    new Semt() { SemtAd = "ERMİŞ", SehirId = 56 },
    new Semt() { SemtAd = "KURTALAN", SehirId = 56 },
    new Semt() { SemtAd = "PERVARİ", SehirId = 56 },
    new Semt() { SemtAd = "ŞİRVAN", SehirId = 56 },
    new Semt() { SemtAd = "AYANCIK", SehirId = 57 },
    new Semt() { SemtAd = "BOYABAT", SehirId = 57 },
    new Semt() { SemtAd = "DİKMEN", SehirId = 57 },
    new Semt() { SemtAd = "DURAĞAN", SehirId = 57 },
    new Semt() { SemtAd = "ERFELEK", SehirId = 57 },
    new Semt() { SemtAd = "GERZE", SehirId = 57 },
    new Semt() { SemtAd = "SARAYDÜZÜ", SehirId = 57 },
    new Semt() { SemtAd = "SİNOP MERKEZ", SehirId = 57 },
    new Semt() { SemtAd = "TÜRKELİ", SehirId = 57 },
    new Semt() { SemtAd = "AKINCILAR", SehirId = 58 },
    new Semt() { SemtAd = "ALTINYAYLA", SehirId = 58 },
    new Semt() { SemtAd = "DİVRİĞİ", SehirId = 58 },
    new Semt() { SemtAd = "DOĞANŞAR", SehirId = 58 },
    new Semt() { SemtAd = "GEMEREK", SehirId = 58 },
    new Semt() { SemtAd = "GÖLOVA", SehirId = 58 },
    new Semt() { SemtAd = "HAFİK", SehirId = 58 },
    new Semt() { SemtAd = "İMRANLI", SehirId = 58 },
    new Semt() { SemtAd = "KANGAL", SehirId = 58 },
    new Semt() { SemtAd = "KOYULHİSAR", SehirId = 58 },
    new Semt() { SemtAd = "SUŞEHRİ", SehirId = 58 },
    new Semt() { SemtAd = "ŞARKIŞLA", SehirId = 58 },
    new Semt() { SemtAd = "ULAŞ", SehirId = 58 },
    new Semt() { SemtAd = "YILDIZELİ", SehirId = 58 },
    new Semt() { SemtAd = "ZARA", SehirId = 58 },
    new Semt() { SemtAd = "MERKEZ", SehirId = 58 },
    new Semt() { SemtAd = "ÇERKEZKÖY", SehirId = 59 },
    new Semt() { SemtAd = "ÇORLU", SehirId = 59 },
    new Semt() { SemtAd = "HAYRABOLU", SehirId = 59 },
    new Semt() { SemtAd = "KAPIKULE", SehirId = 59 },
    new Semt() { SemtAd = "MALKARA", SehirId = 59 },
    new Semt() { SemtAd = "MARMARA EREĞLİSİ", SehirId = 59 },
    new Semt() { SemtAd = "MURATLI", SehirId = 59 },
    new Semt() { SemtAd = "SARAY", SehirId = 59 },
    new Semt() { SemtAd = "SÜLEYMANPAŞA", SehirId = 59 },
    new Semt() { SemtAd = "ŞARKÖY", SehirId = 59 },
    new Semt() { SemtAd = "AKÇAABAT", SehirId = 60 },
    new Semt() { SemtAd = "ALTINORDU", SehirId = 60 },
    new Semt() { SemtAd = "ARSİN", SehirId = 60 },
    new Semt() { SemtAd = "BEŞİKDÜZÜ", SehirId = 60 },
    new Semt() { SemtAd = "ÇARŞAMBA", SehirId = 60 },
    new Semt() { SemtAd = "DERELİ", SehirId = 60 },
    new Semt() { SemtAd = "DÜZKÖY", SehirId = 60 },
    new Semt() { SemtAd = "HAYRAT", SehirId = 60 },
    new Semt() { SemtAd = "KÖPRÜBAŞI", SehirId = 60 },
    new Semt() { SemtAd = "MAÇKA", SehirId = 60 },
    new Semt() { SemtAd = "OF", SehirId = 60 },
    new Semt() { SemtAd = "SALPAZARI", SehirId = 60 },
    new Semt() { SemtAd = "SÜRMENE", SehirId = 60 },
    new Semt() { SemtAd = "TONYA", SehirId = 60 },
     new Semt() { SemtAd = "AKÇAABAT", SehirId = 61 },
    new Semt() { SemtAd = "ARAKLI", SehirId = 61 },
    new Semt() { SemtAd = "ARSİN", SehirId = 61 },
    new Semt() { SemtAd = "BEŞİKDÜZÜ", SehirId = 61 },
    new Semt() { SemtAd = "ÇARŞAMBA", SehirId = 61 },
    new Semt() { SemtAd = "DERNEKPAZARI", SehirId = 61 },
    new Semt() { SemtAd = "DÜZKÖY", SehirId = 61 },
    new Semt() { SemtAd = "HAYRAT", SehirId = 61 },
    new Semt() { SemtAd = "KÖPRÜBAŞI", SehirId = 61 },
    new Semt() { SemtAd = "MAÇKA", SehirId = 61 },
    new Semt() { SemtAd = "OF", SehirId = 61 },
    new Semt() { SemtAd = "SÜRMENE", SehirId = 61 },
    new Semt() { SemtAd = "TONYA", SehirId = 61 },
    new Semt() { SemtAd = "TRABZON MERKEZ", SehirId = 61 },
    new Semt() { SemtAd = "VAKFIKEBİR", SehirId = 61 },
    new Semt() { SemtAd = "YOMRA", SehirId = 61 },
    new Semt() { SemtAd = "TUNCELİ MERKEZ", SehirId = 62 },
    new Semt() { SemtAd = "ÇEMİŞGEZEK", SehirId = 62 },
    new Semt() { SemtAd = "HOZAT", SehirId = 62 },
    new Semt() { SemtAd = "MAZGİRT", SehirId = 62 },
    new Semt() { SemtAd = "NAZIMİYE", SehirId = 62 },
    new Semt() { SemtAd = "OVACIK", SehirId = 62 },
    new Semt() { SemtAd = "PERTEK", SehirId = 62 },
    new Semt() { SemtAd = "PÜLÜMÜR", SehirId = 62 },
    new Semt() { SemtAd = "AKÇAKALE", SehirId = 63 },
    new Semt() { SemtAd = "BİRECİK", SehirId = 63 },
    new Semt() { SemtAd = "BOZOVA", SehirId = 63 },
    new Semt() { SemtAd = "CEYLANPINAR", SehirId = 63 },
    new Semt() { SemtAd = "EYYÜBİYE", SehirId = 63 },
    new Semt() { SemtAd = "HALFETİ", SehirId = 63 },
    new Semt() { SemtAd = "HALİLİYE", SehirId = 63 },
    new Semt() { SemtAd = "HARRAN", SehirId = 63 },
    new Semt() { SemtAd = "HİLVAN", SehirId = 63 },
    new Semt() { SemtAd = "KARAKÖPRÜ", SehirId = 63 },
    new Semt() { SemtAd = "SİVEREK", SehirId = 63 },
    new Semt() { SemtAd = "SURUÇ", SehirId = 63 },
    new Semt() { SemtAd = "VİRANŞEHİR", SehirId = 63 },
    new Semt() { SemtAd = "BANAZ", SehirId = 64 },
    new Semt() { SemtAd = "EŞME", SehirId = 64 },
    new Semt() { SemtAd = "KARAHALLI", SehirId = 64 },
    new Semt() { SemtAd = "SİVASLI", SehirId = 64 },
    new Semt() { SemtAd = "ULUBEY", SehirId = 64 },
    new Semt() { SemtAd = "UŞAK MERKEZ", SehirId = 64 },
    new Semt() { SemtAd = "BAHÇESARAY", SehirId = 65 },
    new Semt() { SemtAd = "BAŞKALE", SehirId = 65 },
    new Semt() { SemtAd = "ÇALDIRAN", SehirId = 65 },
    new Semt() { SemtAd = "ÇATAK", SehirId = 65 },
    new Semt() { SemtAd = "EDREMİT", SehirId = 65 },
    new Semt() { SemtAd = "ERCİŞ", SehirId = 65 },
    new Semt() { SemtAd = "GEVAŞ", SehirId = 65 },
    new Semt() { SemtAd = "GÜRPINAR", SehirId = 65 },
    new Semt() { SemtAd = "İPEKYOLU", SehirId = 65 },
    new Semt() { SemtAd = "MURADİYE", SehirId = 65 },
    new Semt() { SemtAd = "ÖZALP", SehirId = 65 },
    new Semt() { SemtAd = "SARAY", SehirId = 65 },
    new Semt() { SemtAd = "TUŞBA", SehirId = 65 },
    new Semt() { SemtAd = "AKDAĞMADENİ", SehirId = 66 },
    new Semt() { SemtAd = "AYDINCIK", SehirId = 66 },
    new Semt() { SemtAd = "BOĞAZLIYAN", SehirId = 66 },
    new Semt() { SemtAd = "ÇANDIR", SehirId = 66 },
    new Semt() { SemtAd = "ÇAYIRALAN", SehirId = 66 },
    new Semt() { SemtAd = "ÇEKEREK", SehirId = 66 },
    new Semt() { SemtAd = "KADIŞEHRİ", SehirId = 66 },
    new Semt() { SemtAd = "SARAYKENT", SehirId = 66 },
    new Semt() { SemtAd = "SARIKAYA", SehirId = 66 },
    new Semt() { SemtAd = "SORGUN", SehirId = 66 },
    new Semt() { SemtAd = "ŞEFAATLİ", SehirId = 66 },
    new Semt() { SemtAd = "YENİFAKILI", SehirId = 66 },
    new Semt() { SemtAd = "YERKÖY", SehirId = 66 },
    new Semt() { SemtAd = "ALAPLI", SehirId = 67 },
    new Semt() { SemtAd = "ÇAYCUMA", SehirId = 67 },
    new Semt() { SemtAd = "DEVREK", SehirId = 67 },
    new Semt() { SemtAd = "EREĞLİ", SehirId = 67 },
    new Semt() { SemtAd = "GÖKÇEBEY", SehirId = 67 },
    new Semt() { SemtAd = "KİLİMLİ", SehirId = 67 },
    new Semt() { SemtAd = "KOZLU", SehirId = 67 },
    new Semt() { SemtAd = "AĞAÇÖREN", SehirId = 68 },
    new Semt() { SemtAd = "ESKİL", SehirId = 68 },
    new Semt() { SemtAd = "GÜLAĞAÇ", SehirId = 68 },
    new Semt() { SemtAd = "GÜZELYURT", SehirId = 68 },
    new Semt() { SemtAd = "ORTAKÖY", SehirId = 68 },
    new Semt() { SemtAd = "SARIYAHŞİ", SehirId = 68 },
    new Semt() { SemtAd = "SULTANHANI", SehirId = 68 },
     new Semt() { SemtAd = "AYDINTEPE", SehirId = 69 },
    new Semt() { SemtAd = "DEMİRÖZÜ", SehirId = 69 },
    new Semt() { SemtAd = "BAYBURT MERKEZ", SehirId = 69 },
    new Semt() { SemtAd = "AYRANCI", SehirId = 70 },
    new Semt() { SemtAd = "BAŞYAYLA", SehirId = 70 },
    new Semt() { SemtAd = "ERMENEK", SehirId = 70 },
    new Semt() { SemtAd = "KARAMAN MERKEZ", SehirId = 70 },
    new Semt() { SemtAd = "KAZIMKARABEKİR", SehirId = 70 },
    new Semt() { SemtAd = "SARIVELİLER", SehirId = 70 },
    new Semt() { SemtAd = "BAHŞILI", SehirId = 71 },
    new Semt() { SemtAd = "BALIŞEYH", SehirId = 71 },
    new Semt() { SemtAd = "ÇELEBİ", SehirId = 71 },
    new Semt() { SemtAd = "DELİCE", SehirId = 71 },
    new Semt() { SemtAd = "KARAKEÇİLİ", SehirId = 71 },
    new Semt() { SemtAd = "KESKİN", SehirId = 71 },
    new Semt() { SemtAd = "KIRIKKALE MERKEZ", SehirId = 71 },
    new Semt() { SemtAd = "SULAKYURT", SehirId = 71 },
    new Semt() { SemtAd = "YAHŞİHAN", SehirId = 71 },
    new Semt() { SemtAd = "BEŞİRİ", SehirId = 72 },
    new Semt() { SemtAd = "GERCÜŞ", SehirId = 72 },
    new Semt() { SemtAd = "HASANKEYF", SehirId = 72 },
    new Semt() { SemtAd = "KOZLUK", SehirId = 72 },
    new Semt() { SemtAd = "SASON", SehirId = 72 },
     new Semt() { SemtAd = "BEYTÜŞŞEBAP", SehirId = 73 },
    new Semt() { SemtAd = "CİZRE", SehirId = 73 },
    new Semt() { SemtAd = "GÜÇLÜKONAK", SehirId = 73 },
    new Semt() { SemtAd = "İDİL", SehirId = 73 },
    new Semt() { SemtAd = "SİLOPİ", SehirId = 73 },
    new Semt() { SemtAd = "ŞIRNAK MERKEZ", SehirId = 73 },
    new Semt() { SemtAd = "AMASRA", SehirId = 74 },
    new Semt() { SemtAd = "KURUCAŞİLE", SehirId = 74 },
    new Semt() { SemtAd = "ULUS", SehirId = 74 },
    new Semt() { SemtAd = "ÇILDIR", SehirId = 75 },
    new Semt() { SemtAd = "DAMAL", SehirId = 75 },
    new Semt() { SemtAd = "GÖLE", SehirId = 75 },
    new Semt() { SemtAd = "HANAK", SehirId = 75 },
    new Semt() { SemtAd = "POSOF", SehirId = 75 },
     new Semt() { SemtAd = "ARALIK", SehirId = 76 },
    new Semt() { SemtAd = "KARAKOYUNLU", SehirId = 76 },
    new Semt() { SemtAd = "TUZLUCA", SehirId = 76 },
    new Semt() { SemtAd = "ALTINOVA", SehirId = 77 },
    new Semt() { SemtAd = "ARMUTLU", SehirId = 77 },
    new Semt() { SemtAd = "ÇINARCIK", SehirId = 77 },
    new Semt() { SemtAd = "ÇIFTLİKKÖY", SehirId = 77 },
    new Semt() { SemtAd = "TERMAL", SehirId = 77 },
     new Semt() { SemtAd = "EFLANİ", SehirId = 78 },
    new Semt() { SemtAd = "ESKİPAZAR", SehirId = 78 },
    new Semt() { SemtAd = "OVACIK", SehirId = 78 },
    new Semt() { SemtAd = "SAFRANBOLU", SehirId = 78 },
    new Semt() { SemtAd = "YENİCE", SehirId = 78 },
    new Semt() { SemtAd = "ELBEYLİ", SehirId = 79 },
    new Semt() { SemtAd = "MUSABEYLİ", SehirId = 79 },
    new Semt() { SemtAd = "POLATELİ", SehirId = 79 },
    new Semt() { SemtAd = "BAHÇE", SehirId = 80 },
    new Semt() { SemtAd = "DÜZİÇİ", SehirId = 80 },
    new Semt() { SemtAd = "HASANBEYLİ", SehirId = 80 },
    new Semt() { SemtAd = "KADİRLİ", SehirId = 80 },
    new Semt() { SemtAd = "SUMBAS", SehirId = 80 },
    new Semt() { SemtAd = "TOPRAKKALE", SehirId = 80 },
     new Semt() { SemtAd = "AKÇAKOCA", SehirId = 81 },
    new Semt() { SemtAd = "CUMAYERİ", SehirId = 81 },
    new Semt() { SemtAd = "GÖLYAKA", SehirId = 81 },
    new Semt() { SemtAd = "GÜMÜŞOVA", SehirId = 81 },
    new Semt() { SemtAd = "KAYNAŞLI", SehirId = 81 },
    new Semt() { SemtAd = "YIĞILCA", SehirId = 81 },    
    new Semt() { SemtAd = "PINARBAŞI", SehirId = 38 },

            };
            foreach (var item in semt)
            {
                context.Semts.Add(item);
            }
            context.SaveChanges();

            var mahalle = new List<Mahalle>();
            for(int i = 1; i < 935; i++)
            {
                Mahalle mahalle1 = new Mahalle() { MahalleAd = "Atatürk", SemtId = i };
                Mahalle mahalle2 = new Mahalle() { MahalleAd = "Cumhuriyet", SemtId = i };
                Mahalle mahalle3 = new Mahalle() { MahalleAd = "Fevzi Çakmak", SemtId = i };
                Mahalle mahalle4 = new Mahalle() { MahalleAd = "İnönü", SemtId = i };
                Mahalle mahalle5 = new Mahalle() { MahalleAd = "Mehmet Akif Ersoy", SemtId = i };
                Mahalle mahalle6 = new Mahalle() { MahalleAd = "Mustafa Kemal", SemtId = i };
                Mahalle mahalle7 = new Mahalle() { MahalleAd = "Namık Kemal", SemtId = i };
                Mahalle mahalle8 = new Mahalle() { MahalleAd = "Orhanlı", SemtId = i };
                Mahalle mahalle9 = new Mahalle() { MahalleAd = "Turgut Özal", SemtId = i };
                Mahalle mahalle10 = new Mahalle() { MahalleAd = "Yavuz Sultan Selim", SemtId = i };

                Mahalle mahalle11 = new Mahalle() { MahalleAd = "Akköprü", SemtId = i };
                Mahalle mahalle12 = new Mahalle() { MahalleAd = "Aydınlıkevler", SemtId = i };
                Mahalle mahalle13 = new Mahalle() { MahalleAd = "Batıkent", SemtId = i };
                Mahalle mahalle14 = new Mahalle() { MahalleAd = "Demetevler", SemtId = i };
                Mahalle mahalle15 = new Mahalle() { MahalleAd = "Dikimevi", SemtId = i };
                Mahalle mahalle16 = new Mahalle() { MahalleAd = "Eryaman", SemtId = i };
                Mahalle mahalle17 = new Mahalle() { MahalleAd = "Sentepe", SemtId = i };
                Mahalle mahalle18 = new Mahalle() { MahalleAd = "Sincan Yenikent", SemtId = i };
                Mahalle mahalle19 = new Mahalle() { MahalleAd = "Siteler", SemtId = i};
                Mahalle mahalle20 = new Mahalle() { MahalleAd = "Tuzluçayır", SemtId = i };
                mahalle.Add(mahalle1);
                mahalle.Add(mahalle2);
                mahalle.Add(mahalle3);
                mahalle.Add(mahalle4);
                mahalle.Add(mahalle5);
                mahalle.Add(mahalle6);
                mahalle.Add(mahalle7);
                mahalle.Add(mahalle8);
                mahalle.Add(mahalle9);
                mahalle.Add(mahalle10);
                mahalle.Add(mahalle11);
                mahalle.Add(mahalle12);
                mahalle.Add(mahalle13);
                mahalle.Add(mahalle14);
                mahalle.Add(mahalle15);
                mahalle.Add(mahalle16);
                mahalle.Add(mahalle17);
                mahalle.Add(mahalle18);
                mahalle.Add(mahalle19);
                mahalle.Add(mahalle20);


            }

            
            foreach (var item in mahalle)
            {
                context.Mahalles.Add(item);
            }
            context.SaveChanges();

            var durum = new List<Durum>()
            {
                new Durum() {DurumAd="KIRALIK" },
                new Durum() {DurumAd="SATILIK" }
                
            };
            foreach (var item in durum)
            {
                context.Durums.Add(item);
            }
            context.SaveChanges();

            var tip = new List<Tip>()
            {
                new Tip() {TipAd="EV",DurumId=1 },
                 new Tip() {TipAd="DÜKKAN",DurumId=1 },
                 new Tip() {TipAd="EV",DurumId=2 },
                 new Tip() {TipAd="DÜKKAN",DurumId=2 },
            };
            foreach (var item in tip)
            {
                context.Tips.Add(item);
            }
            context.SaveChanges();
            var ilan = new List<Ilan>()
            {
                new Ilan() {Acıklama="ev güzel",Adres="şan sokak",OdaSayisi=5,BanyoSayisi=2,Kredi=true,Fiyat=25000,MahalleId=1,SemtId=1,SehirId=1,DurumId=1,TipId=1,Alan=250,Telefon="444 04 444",Kat="2.kat",UserName="alican" },
                 new Ilan() {Acıklama="ev güzel 1",Adres="can sokak",OdaSayisi=3,BanyoSayisi=1,Kredi=true,Fiyat=2000000,MahalleId=2,SemtId=2,SehirId=2,DurumId=2,TipId=4,Alan=150,Telefon="444 04 444",Kat="5.kat",UserName="ahmetcan" },
            };
            foreach (var item in ilan)
            {
                context.Ilans.Add(item);
            }
            context.SaveChanges();
            var resim = new List<Resim>()
            {
                new Resim() {ResimAd="slide1.jpg",IlanId=1 },
                new Resim() {ResimAd="slide2.jpg",IlanId=1 },
                new Resim() {ResimAd="slide3.jpg",IlanId=2 },
            };
            foreach (var item in resim)
            {
                context.Resims.Add(item);
            }
            context.SaveChanges();
            base.Seed(context); 
        }
    }
}